### ISSUE TITLE
Runtime / script issue

### ISSUE THREAD

**Issue by kentsommer** [vtsynergy/CU2CL#1]
I've successfully installed CU2CL and it built llvm and clang and itself without issue. However, upon trying to actually run the cu2cl_translate.sh script I get the following error:
- fatal error: 'cuda_runtime.h' file not found

I know CUDA is installed correctly as I've used it to build OpenCV with CUDA support enabled from source and had no issues. I have a symlink to /usr/local/cuda-8.0 as /usr/local/cuda to make sure it is found correctly, however, I've been unable to fix the above error. I am using CUDA 8rc, however, this issue does not appear to be because of incompatibility. Any input would be appreciated!

**Comment by kentsommer** [comment]
Solved.

**Comment by BeauJoh** [comment]
Could you tell me how you solved this? I'm experiencing it now.
