### ISSUE TITLE
Capable of compiling Caffe to OpenCL?

### ISSUE THREAD

**Issue by dashesy** [vtsynergy/CU2CL#2]
I am looking for a solution to run CUDA code on CPU, just to make the code portable enough to be testable. I have looked at multiple solutions, NVIDIA no longer supports emulation, and most other [emulation frameworks](https://github.com/gtcasl/gpuocelot) are dead.
At this point it seems the best option is to compile CUDA to OpenCL which can run on CPU.

How far is CU2CL to be able to compile [caffe](https://github.com/BVLC/caffe)?

**Comment by psath** [comment]
While we have not tried to translate Caffe, a cursory glance at the solver kernels indicates they are  templated. At this time CU2CL does not support automatic template specialization and generating the appropriate OpenCL C kernel for each such specialization. Aside from the templates, if the remainder of the project is not too C++-heavy, CU2CL should do well with the remaining CUDA boilerplate. Once an implementation of [OpenCL Kernel C++](https://www.khronos.org/news/press/khronos-releases-opencl-2.2-provisional-spec-opencl-c-kernel-language) is generally available, the CUDA C++ --> OpenCL C conversion will be less cumbersome.

**Comment by dashesy** [comment]
Thanks
