### ISSUE TITLE
Unable to get expected output from translated code

### ISSUE THREAD

**Issue by GMKB** [vtsynergy/CU2CL#5]
Hi!
I'm able to translate a simple **add2numbers.cu**  program using cu2cl-tool. But when I compile and execute the translated code, I am not getting the expected output. When I checked with the code, I found out that "**size_t localWorkSize[3]**" wasn't assigned any value. So I manually assigned the values to this. And this served the purpose. 
Should I fix this to every translated program or am I missing any options while translating the program?
Could I get any pointers to this?

Commands used to run the program:
$ cu2cl-tool add2numbers.cu -import-gcc-paths -- -I /usr/local/cuda-7.5/targets/x86_64-linux/include/ &> output.txt
$ g++ daxpy.cu-cl.cpp -c
$ gcc cu2cl_util.c -c
$ gcc add2numbers.cu-cl.o cu2cl_util.o -lOpenCL

Here is the program and translated code.
[add2numbers.zip](https://github.com/vtsynergy/CU2CL/files/4479550/add2numbers.zip)

**Comment by psath** [comment]
Thanks for the test case. The underlying issue was a corner case for 1D, integer constant block sizes that was missing its string generation, it should be fixed now.

Please pull and confirm the fix works for you as well, then I will close the issue.

**Comment by GMKB** [comment]
The fix works for me now.
Thank you.
