### ISSUE TITLE
Running cu2cl-tool on cuda samples under /usr/local/cuda

### ISSUE THREAD

**Issue by GMKB** [vtsynergy/CU2CL#6]
I am testing cu2cl-tool for further development. Normally I run cuda samples using make file. But how do I run tool on those samples? And run translated code. 
[vectorAdd.zip](https://github.com/vtsynergy/CU2CL/files/4482068/vectorAdd.zip)

**Comment by psath** [comment]
I don't understand your question. You are running the tool and linking the new files appropriately in #5 . Follow the same approach and modify the makefiles to suit.

CU2CL cannot make changes to files in protected system directories, but you can copy to userspace, translate, build, and run from there.

We cannot provide post-translation support or warranty for Nvidia samples, or any codes, as stated in the License. Please only create issues for defects or inadequacies of the tool. If you wish to discuss a paid service agreement for such support, please contact cu2cl-info@cs.vt.edu.
